linters-settings:
  gocritic:
    enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style
    disabled-checks:
    - ifElseChain
    settings:
      hugeParam:
        sizeThreshold: 512
  gocyclo:
    min-complexity: 20
  gosec:
    excludes:
      - G115
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: true

linters:
  disable-all: true
  enable:
  - bodyclose
  - copyloopvar
  - errcheck
  - gocritic
  - gocyclo
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - noctx
  - nolintlint
  - staticcheck
  - typecheck
  - unused

issues:
  exclude-rules:
  - path: _test\.go$
    linters:
    - bodyclose
    - noctx
