version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - noctx
    - nolintlint
    - staticcheck
    - unused
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        hugeParam:
          sizeThreshold: 512
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G115
    nolintlint:
      require-explanation: false
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - noctx
        path: _test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
